### ISSUE TITLE
resource for Proactor model

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/open-source-spec#8]

**Comment by CodeBear801** [comment]
![image](https://user-images.githubusercontent.com/16873751/104974908-1c5d7300-59ae-11eb-8d17-a669a80401f1.png)

![image](https://user-images.githubusercontent.com/16873751/104974914-23848100-59ae-11eb-9623-4f029e3daf56.png)

![image](https://user-images.githubusercontent.com/16873751/104974925-2b442580-59ae-11eb-933d-b652bd881599.png)

**Comment by CodeBear801** [comment]
![image](https://user-images.githubusercontent.com/16873751/104975121-9f7ec900-59ae-11eb-8428-26ebee43759d.png)

**Comment by CodeBear801** [comment]
![image](https://user-images.githubusercontent.com/16873751/104975619-0650b200-59b0-11eb-8fc3-0f01a939ff0e.png)

**Comment by perryliudd** [comment]
<img width="1583" alt="image" src="https://github.com/Telenav/open-source-spec/assets/110483859/5adae72d-376e-4080-843c-4ab7e6d645ae">
